apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clinet-pvc-name
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
