apiVersion: v1
kind: Secret
metadata:
  name: client-secret-name
type: bootstrap.kubernetes.io/token
stringData:
  DB_HOST: demo-postgresql-db-user.db.digitalocean.com
  DB_USER: admin
  DB_PASSWORD: 123456
  DB_PORT: "25000"